modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="srv"
version="2.7"
displayName="The SRV Mod"
displayURL="https://hedgehawk11.github.io"
logoFile="logo.png"
credits="YOUTUBE"
authors="Hedgehawk11"
description="Made with no regrets by Hedgehawk11"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.srv]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.srv]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration